[package]
authors = ["gyu-don <takumi.kt@gmail.com>"]
description = "OpenQASM3 parser"
edition = "2021"
license = "Apache-2.0"
name = "openqasm3"
publish = true
repository = "https://github.com/gyu-don/openqasm3-rs"
version = "0.0.1"
[dependencies]
chumsky = "0.8.0"
ordered-float = "3.0.0"
